- block:
  - set_fact:
      values: "{{ vars['map'][item] }}"

  - set_fact:
      "{{ item }}": "{{ value[0] }}"
    with_items: "{{ [values] }}"
    loop_control:
      loop_var: value
    when: vars[item] == value[1]
  when: vars['map'][item] is defined
